apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: lab-ns-vendas
  labels:
    app: db
    tier: data
spec:
  containers:
    - name: nginx
      image: nginx:1.25-alpine
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: lab-ns-vendas
spec:
  selector:
    app: db
  ports:
    - port: 80
      targetPort: 80
