apiVersion: v1
kind: Pod
metadata:
  name: nginx-incomplete
  namespace: lab-objects-01
  labels:
    app: obj-lab
spec:
  containers:
    - name: nginx
      # Complete: adicione image aqui (mesmo nível que name e ports)
      ports:
        - containerPort: 80
